name: "API: Publish Docker Image"

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.get-version.outputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout Private Actions
        uses: actions/checkout@v4
        with:
          repository: bytethat/github-actions
          path: ./.github/private-actions
          token: ${{ secrets.GH_ACTIONS_PAT }}

      - name: Resolve Artifact Version
        id: get-version
        uses: ./.github/private-actions/artifact-get-version
        with:
          artifact-id: 'gsis-api-gateway'
          artifact-type: 'docker'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Private Docker Registry
        uses: docker/login-action@v3
        with:
          registry: registry.bytethat.gr
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.bytethat.gr/gsis-api-gateway:${{ steps.get-version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Persist Artifact Version
        uses: ./.github/private-actions/artifact-set-version
        with:
          artifact-id: 'gsis-api-gateway'
          artifact-type: 'docker'
          version: '${{ steps.get-version.outputs.version }}'
  deploy:
    name: Deploy to Portainer
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Actions
        uses: actions/checkout@v4
        with:
          repository: bytethat/github-actions
          path: ./.github/private-actions
          token: ${{ secrets.GH_ACTIONS_PAT }}
      - name: Deploy to Portainer Stack
        uses: ./.github/private-actions/portainer-deploy
        with:
          portainer_stack_repo: 'bytethat/portainer-deployments'
          GH_PAT: ${{ secrets.GH_PORTAINER_WRITE_PAT }}
          path: 'gsis-api-gateway/production/docker-compose.yml'
          registry: 'registry.bytethat.gr'
          image: 'gsis-api-gateway'
          version: '${{ needs.build-and-push.outputs.version }}'
          portainer_webhook_url: ${{ secrets.PORTAINER_WEBHOOK_URL }}